../rtl/ex_stage.v
../rtl/id_stage.v
../rtl/forwarding.v

../rtl/if_stage_sync.v
../rtl/mem_stage_sync.v
../rtl/top_rv32_sync.v
../rtl/registers_file.v
../rtl/imem_sync.v
../rtl/dma_regfile.v
../rtl/cpu_mmio_to_apb_bridge.v
../rtl/dma_tx_engine.v
../rtl/dma_rx_engine.v

#../rtl/top_rv32.v
#../rtl/if_stage.v
#../rtl/mem_stage.v

../rtl/DMEM_ip.v
../rtl/dmem_ip_wrapper.v
../rtl/rv32_soc_top.v

../rtl/block_buffer.v
../rtl/frequency_counter.v
../rtl/input_collect_unit.v
../rtl/symbol_list_builder.v
../rtl/code_length_builder.v
../rtl/canonical_code_generator.v
../rtl/huffman_builder.v
../rtl/header_formatter.v
../rtl/payload_emitter.v
../rtl/stream_output_interface.v
../rtl/emit_backend.v
../rtl/control_fsm.v
../rtl/dynamic_huffman_encoder.v
../rtl/wrapper.v
../rtl/wrapper_rx.v
../rtl/bit_packer_128.v
../rtl/bit_depacker_128.v
../rtl/huffman_block_parser.v
../rtl/HUFFMAN_DECODE_TABLE_IP.v
../rtl/huffman_block_decoder.v
../rtl/rx_byte_packer_32.v
../rtl/apb_huffman_rx_if.v
../rtl/apb_huffman_aes_rx_top.v
#../rtl/apb_huffman_aes_tx_rx_top.v
../rtl/huffman_aes_tx_top.v
../rtl/apb_huffman_tx_if.v
../rtl/aes128_key_expansion.v
../rtl/aes128_cipher_core.v
../rtl/aes128_cipher_top.v
../rtl/aes128_cipher_core_inv.v
../rtl/aes128_key_expansion_inv.v
../rtl/aes128_cipher_inv_top.v
#../rtl/AES_top.v
../rtl/apb_huffman_aes_tx_top.v
