# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/sim/.Xil/Vivado-55880-An/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z020clg484-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName work
    rt::set_parameter defaultVhdlWorkLib work

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl
    H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/vivado/build/rv32_soc_synth_tx/ip/IMEM_ip
    H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/vivado/build/rv32_soc_synth_tx/ip/DMEM_ip
    H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/vivado/build/rv32_soc_synth_tx
  } -define {VIVADO_USE_IP FPGA_TX_ONLY} H:/From_software/Vivado/Vivado/Vivado/2024.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
      rt::read_verilog -include {
    H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl
    H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/vivado/build/rv32_soc_synth_tx/ip/IMEM_ip
    H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/vivado/build/rv32_soc_synth_tx/ip/DMEM_ip
    H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/vivado/build/rv32_soc_synth_tx
  } -define {VIVADO_USE_IP FPGA_TX_ONLY} {
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/sim/.Xil/Vivado-55880-An/realtime/IMEM_ip_stub.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/sim/.Xil/Vivado-55880-An/realtime/DMEM_ip_stub.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/aes128_cipher_core.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/aes128_cipher_top.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/aes128_key_expansion.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/apb_huffman_aes_tx_top.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/apb_huffman_tx_if.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/bit_packer_128.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/block_buffer.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/canonical_code_generator.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/code_length_builder.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/control_fsm.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/cpu_mmio_to_apb_bridge.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/dma_regfile.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/dma_tx_engine.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/dmem_ip_wrapper.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/dynamic_huffman_encoder.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/emit_backend.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/ex_stage.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/forwarding.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/frequency_counter.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/header_formatter.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/huffman_aes_tx_top.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/huffman_builder.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/id_stage.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/if_stage_sync.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/imem_sync.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/input_collect_unit.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/mem_stage_sync.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/mode_decision_logic.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/payload_emitter.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/registers_file.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/rv32_soc_top.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/stream_output_interface.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/symbol_list_builder.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/top_rv32_sync.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/uart_dmem_loader.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/uart_rx.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/uart_tx.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/wrapper.v
      H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/rtl/rv32_soc_fpga_demo_top.v
    }
      rt::read_vhdl -lib xpm H:/From_software/Vivado/Vivado/Vivado/2024.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top rv32_soc_fpga_demo_top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "H:/Academic/senior_project/DATN/work/luc/AES_huffman_all6/sim/.Xil/Vivado-55880-An/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
   return -code "error" $rt::result
 }
}
